* PROVA

Durante a prova fora feito a correção do código python onde se encontrava o erro na segunda aplicação. E foi subido um CI docker conectado no docker hub no git actions.
